const menu = [
    {
        id: 1,
        nombre : "Banchan",
        precio: 27500,
        gramaje: "450g",
        descripcion: "It's a set of dishes that serve to accompany main courses to generate a contrast of flavors. They are made from kimchi, cucumber, spinach, soybean sprouts, radish, eggplant, beans, carrots, seaweed, among others.",
        categoria: "entradas",
        foto:"img/preparaciones/banchan.jpg",
        kcal: 130,
        carbohidrados: 18,
        grasas: 4,
        proteina: 12
    },
    {
        id: 2,
        nombre : "Kimchi",
        precio: 25000,
        gramaje: "250g",
        descripcion: "It's a traditional Korean dish consisting of fermented cabbage and radishes, seasoned with garlic, ginger, red pepper, and other spices. It is consumed as a side dish to main courses. Besides being delicious, kimchi is also known for its health benefits, thanks to its content of vitamins, antioxidants, and probiotics.",
        categoria: "entradas",
        foto:"img/preparaciones/kimchi.jpg",
        kcal: 22,
        carbohidrados: 4.15,
        grasas: 0.32,
        proteina: 1.7
    },
    {
        id: 3,
        nombre : "Pajeon",
        precio: 20000,
        gramaje: "200g",
        descripcion: "It's a pancake made from wheat flour and green onions. Due to its versatility, it can be made with various ingredients such as seafood, shrimp, squid, vegetables, or others, according to the customer's taste.",
        categoria: "entradas",
        foto:"img/preparaciones/pajeon.jpg",
        kcal: 60,
        carbohidrados: 7.3,
        grasas: 2,
        proteina: 3.8
    },
    {
        id: 4,
        nombre : "Kimbap",
        precio: 28000,
        gramaje: "300g",
        descripcion: "Kimbap is a rice roll wrapped in nori seaweed. It is very versatile in its accompaniment, so it can be made with vegetables like carrots, spinach, and radishes, meat products, seafood products, kimchi, egg, or avocado.",
        categoria: "entradas",
        foto:"img/preparaciones/kimbap1.jpg",
        kcal: 38,
        carbohidrados: 2.7,
        grasas: 2.4,
        proteina: 1.5
    },
    {
        id: 5,
        nombre : "SSAM / SAAM",
        precio: 25000,
        gramaje: "450g",
        descripcion: "SSAM is a set of dishes with various ingredients and flavors. It will be wrapped in a lettuce leaf. It contains grilled meat (pork belly), green onions, rice, ssamjang (paste), among others.",
        categoria: "entradas",
        foto:"img/preparaciones/ssam.jpg",
        kcal: 95,
        carbohidrados: 20,
        grasas: 8,
        proteina: 10
    },
    {
        id: 6,
        nombre : "Mandu",
        precio: 27000,
        gramaje: "10 units",
        descripcion: "Dumpling or steamed or fried turnover, filled with meat and vegetables. This may include: pork, beef, chicken, tofu, chives, mushrooms, among others.",
        categoria: "entradas",
        foto:"img/preparaciones/mandu.jpg",
        kcal: 194,
        carbohidrados: 24,
        grasas: 6,
        proteina: 11
    },
    {
        id: 7,
        nombre : "Bibimbap",
        precio: 50000,
        gramaje: "450g",
        descripcion: "Dish made from rice, sautéed vegetables, meat (beef, chicken, or pork), egg, gochujang (fermented chili paste and condiments), and kimchi (optional).",
        categoria: "platos fuertes",
        foto:"img/preparaciones/Bibimbap.jpg",
        kcal: 400,
        carbohidrados: 30,
        grasas: 17,
        proteina: 25
    },
    {
        id: 8,
        nombre : "Japchae",
        precio: 30000,
        gramaje: "300g",
        descripcion: "Dish based on cellophane noodles accompanied by rib eye, carrots, spinach, bell pepper, onion, and shiitake mushrooms.",
        categoria: "platos fuertes",
        foto:"img/preparaciones/japchae.jpg",
        kcal: 348,
        carbohidrados: 51.5,
        grasas: 11.5,
        proteina: 11.5
    },
    {
        id: 9,
        nombre : "Samgyeopsal (Barbacoa)",
        precio: 100000,
        gramaje: "600g",
        descripcion: "Roast accompanied by slices of pork belly, pork loin, carrot, cabbage, green onions, and romaine lettuce.",
        categoria: "platos fuertes",
        foto:"img/preparaciones/Samgyeopsal.jpg",
        kcal: 333,
        carbohidrados: 0,
        grasas: 28,
        proteina: 18
    },
    {
        id: 10,
        nombre : "Budae Jjigae",
        precio: 55000,
        gramaje: "400g",
        descripcion: "Typical Korean soup, similar to a stew, accompanied by Frankfurt sausages, tofu, enoki mushrooms, oyster mushrooms, shiitake mushrooms, aged kimchi, and ramen noodles.",
        categoria: "platos fuertes",
        foto:"img/preparaciones/Budae_Jjigae.jpg",
        kcal: 552,
        carbohidrados: 91,
        grasas: 16,
        proteina: 10
    },
    {
        id: 11,
        nombre : "Jajangmyeon",
        precio: 45000,
        gramaje: "350g",
        descripcion: "Thick wheat noodles, covered in thick sauce made from chunjang, meat, chopped vegetables and only occasionally seafood, pork belly, onion, zucchini, cabbage, garlic, ginger, and paste.",
        categoria: "platos fuertes",
        foto:"img/preparaciones/Jajangmyeon.jpg",
        kcal: 610,
        carbohidrados: 91,
        grasas: 23,
        proteina: 9
    },
    {
        id: 12,
        nombre : "Jjimdak",
        precio: 35000,
        gramaje: "450g",
        descripcion: "Stewed chicken with sweet, salty, and slightly spicy tones. It is accompanied by potatoes, carrots, onion, chili peppers, Korean glass noodles, mushrooms or shiitake mushrooms, green onion, toasted sesame seeds.",
        categoria: "platos fuertes",
        foto:"img/preparaciones/jjimdak.jpg",
        kcal: 465,
        carbohidrados: 61,
        grasas: 14.5,
        proteina: 23.7
    },
    {
        id: 13,
        nombre : "Tteokbokki",
        precio: 19500,
        gramaje: "5 units",
        descripcion: "Dessert made from glutinous rice flour accompanied by nuts, sesame seeds, pine nuts, oil, and sugar. They are consumed as cakes, so they are sweet and come in different flavors.",
        categoria: "postres",
        foto:"img/preparaciones/tteok.jpg",
        kcal: 420,
        carbohidrados: 94,
        grasas: 1.4,
        proteina: 8
    },
    {
        id: 14,
        nombre : "Mochis",
        precio: 23000,
        gramaje: "6 units",
        descripcion: "Dessert made from glutinous rice flour, water, sugar, and cornstarch. Filled with fruits such as strawberry, kiwi, mango, peach, blueberries, and decorated with chocolate or whipped cream.",
        categoria: "postres",
        foto:"img/preparaciones/mochis.jpg",
        kcal: 96,
        carbohidrados: 18,
        grasas: 3,
        proteina: 1
    },
    {
        id: 15,
        nombre : "Dasik",
        precio: 18500,
        gramaje: "6 units",
        descripcion: "Dessert made from cereal flour, honey, sugar, fruit, and yeot, decorated with dasikpan engravings. This dessert is inspired by the real era of the Joseon Dynasty.",
        categoria: "postres",
        foto:"img/preparaciones/dasik.jpg",
        kcal: 123,
        carbohidrados: 23,
        grasas: 3,
        proteina: 1
    },
    {
        id: 16,
        nombre : "Bingsu",
        precio: 22000,
        gramaje: "20g",
        descripcion: "Shaved ice accompanied with jams, syrups, fruits, and toppings.",
        categoria: "postres",
        foto:"img/preparaciones/bingsu.jpg",
        kcal: 97 ,
        carbohidrados: 17,
        grasas: 2.3,
        proteina: 1
    },
    {
        id: 17,
        nombre : "Hoddeok",
        precio: 15000,
        gramaje: "130g",
        descripcion: "Fried pancake commonly filled with a mixture of brown sugar, peanuts, and cinnamon.",
        categoria: "postres",
        foto:"img/preparaciones/Hoddeok.webp",
        kcal: 197,
        carbohidrados: 29.8,
        grasas: 7,
        proteina: 4.1
    },
    {
        id: 18,
        nombre : "Songpyeon",
        precio: 25000,
        gramaje: "6 units",
        descripcion: "Typical dessert consumed in autumn (its special season: Chuseok Harvest Festival).",
        categoria: "postres",
        foto:"img/preparaciones/songpyeon.jpg",
        kcal: 84,
        carbohidrados: 14.7,
        grasas: 1.2,
        proteina: 1.4
    },
    {
        id: 19,
        nombre : "Soju ",
        precio: 40000,
        gramaje: "360 ml",
        descripcion: "It is a distilled liquor made from rice, barley, or sweet potato, offering a smooth and versatile flavor profile. With a balanced alcohol content, it is ideal for accompanying your meals, enhancing the flavors of each bite.",
        categoria: "bebidas",
        foto:"img/preparaciones/Soju-bebida.jpg",
        kcal: 241 ,
        carbohidrados: 45,
        grasas: 0,
        proteina: 0.5
    },
    {
        id: 20,
        nombre : "Makgeolli",
        precio: 50000,
        gramaje: "1.2L",
        descripcion: "Traditional rice-based fermented liquor, characteristic for its milky color and silky body. With subtle flavors of sweet rice, fresh taste, lightness, and a fizzy touch that creates a perfect contrast with your meals.",
        categoria: "bebidas",
        foto:"img/preparaciones/Makgeolli-bebida.jpg",
        kcal: 128,
        carbohidrados: 15,
        grasas: 0,
        proteina: 5
    },
    {
        id: 21,
        nombre : "Sake coreano",
        precio: 60000,
        gramaje: "700ml",
        descripcion: "Traditional Korean rice wine made from rice. It is consumed as an alcoholic beverage with sweet and slightly acidic tones, creating a contrast in the flavors of the food. It can be served cold, warm, or hot.",
        categoria: "bebidas",
        foto:"img/preparaciones/sake-bebida.jpg",
        kcal: 140,
        carbohidrados: 17,
        grasas: 0,
        proteina: 3
    },
    {
        id: 22,
        nombre : "Bokbunja ju",
        precio: 12000,
        gramaje: "300ml",
        descripcion: "Handcrafted beverage made from juicy and aromatic bokbunja berries, also known as Korean mulberries. With fruity sweetness and a subtle touch of acidity, vibrant tone, and an explosion of flavors.",
        categoria: "bebidas",
        foto:"img/preparaciones/bokbunjaJu-bebida.jpg",
        kcal: 300,
        carbohidrados: 36,
        grasas: 0,
        proteina: 0
    },
    {
        id: 23,
        nombre : "Omija Cha",
        precio: 12000,
        gramaje: "300ml",
        descripcion: "Beverage made with vibrant omija berries, which have sweet, salty, sour, bitter, and spicy flavors. This exquisite infusion is created by combining omija berries with pure water and the natural sweetness of honey, resulting in a balanced and refreshing drink.",
        categoria: "bebidas",
        foto:"img/preparaciones/OmijaCha-bebida.jpg",
        kcal: 10,
        carbohidrados: 2,
        grasas: 0,
        proteina: 0
    },
    {
        id: 24,
        nombre : "Bocado de angel",
        precio: 27000,
        gramaje: "8 units",
        descripcion: "Fried dumpling filled with pork rind, shredded meat in coffee BBQ sauce, yuca chips, ripe plantain, caramelized leek, gouda cheese, and mozzarella.",
        categoria: "fusion",
        foto:"img/preparaciones/fusion-bocado-de-angel.webp",
        kcal: 250,
        carbohidrados: 55,
        grasas: 13,
        proteina: 18
    },
    {
        id: 25,
        nombre : "Memorias",
        precio: 27000,
        gramaje: "300",
        descripcion: "Boiled dish composed of chicken, yuca chips, asparagus, scallions, vegetables sautéed in soy sauce infused with coconut: onion, cauliflower, corn, sesame, broccoli, carrot, and ripe plantain.",
        categoria: "fusion",
        foto:"img/preparaciones/fusion-memorias.jpg",
        kcal: 350,
        carbohidrados: 60,
        grasas: 17,
        proteina: 18
    },
    {
        id: 26,
        nombre : "Explosión",
        precio: 13000,
        gramaje: "4 units",
        descripcion: "Snack filled with guava paste, cocoa, and nuts, made with rice and wheat flour covered with toasted almond, peanuts, and pistachios.",
        categoria: "fusion",
        foto:"img/preparaciones/fusion-explosion.jpg",
        kcal: 300,
        carbohidrados: 40,
        grasas: 17,
        proteina: 8
    },
    {
        id: 27,
        nombre : "Camino cafetero",
        precio: 20000,
        gramaje: "150g",
        descripcion: "Fried pancake made from plantain flour filled with cocoa, plantain, coffee sauce reduction with panela, and cinnamon.",
        categoria: "fusion",
        foto:"img/preparaciones/fusion-camino-cafetero.jpg",
        kcal: 220,
        carbohidrados: 35,
        grasas: 14,
        proteina: 6
    },

]